[package]
name = "integrator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
uuid = { version = "0.8.1", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
rusqlite = { version = "0.27", features = ["bundled"] }
